### ISSUE TITLE
"Mauvais nom d'utilisateur ou mot de passe"

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/libreerp_ynh#11]
L'installation c'est bien déroulé mais lors de la connexion j'ai un message d'erreur comme quoi je me serais trompé de nom d'utilisateur (courriel) ou de mot de passe...  
je suis sûr de mon mot de passe, en revanche je n'ai indiqué nul part (pendant la config) mon adresse mail...  est-ce normal ?
![selection_0112](https://user-images.githubusercontent.com/11737560/50172396-46d33280-02f5-11e9-8dcf-d81c4b42b240.png)

**Comment by vincentux** [comment]
Problème résolu.  
En fait il faut juste renseigner "**admin**" dans le champ "Courriel"

**Comment by tissa2636** [comment]
Récupérer mon identifiant 1xbet
