### ISSUE TITLE
Set up issue DataError: new encoding (UTF8)

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/libreerp_ynh#2]
Hi,
I got this error:

> psycopg2.DataError: new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)

I had needed this solution:

https://www.odoo.com/fr_FR/forum/aide-1/question/dataerror-new-encoding-utf8-is-incompatible-with-the-encoding-of-the-template-database-sql-ascii-52124

**Comment by scith** [comment]
Thanks. I suggest we do a full rework of the package. We could include this fix then
https://github.com/YunoHost-Apps/odoo_ynh/issues/3
